baseURL = "https://yax.com/"
languageCode = "en-us"
title = "Yax.com · Build and Host a Website for Free"
paginate = 5 # Number of posts to show before paginating
theme = "bulma" # to use as default theme

enableRobotsTXT = true # Suggested, it generates a robots.txt
googleAnalytics = "UA-5109366-12" # Optional, add tracking Id for analytics
disqusShortname = "" # Optional, add Disqus shortname for comments
SectionPagesMenu = "main" # Enable menu system for lazy bloggers

[params]
  theme_variant = "" # possible value for the theme_variant `cerulean,cosmo,cyborg,darkly,flatly,journal,litera,lumen,lux,materia,minty,pulse,sandstone,simplex,slate,solar,spacelab,superhero,united,yeti`
  description = "The do-it-yourself alternative to Wix and Squarespace." # Suggested, controls default description meta and landing page
  powered_by = "" # Optional, controls name display on footer
  hide_author = false # Optional, set true to hide author name on posts
  images = [] # Suggested, controls default OpenGraph images controls author name display on meta tag
  github  = "DanielKehoe" # Optional, to display link to github account in menu bar
  twitter = "danielkehoe" # Optional, to display link to twitter account in menu bar
  
  [menu]
   [[menu.main]]
        name = "Blog"
        weight = 1
        identifier = "posts"
        url = "/posts/"